config_file: /etc/redpanda/redpanda.yaml
pandaproxy: {}
redpanda:
  admin:
  - address: 0.0.0.0
    port: 9644
  admin_api_tls:
  - cert_file: /opt/workspace/certs/client-cert.pem
    enabled: true
    key_file: /opt/workspace/certs/client-privkey.pem
    require_client_auth: true
    truststore_file: /opt/workspace/certs/ca-cert.pem
  advertised_kafka_api:
  - address: host.docker.internal
    port: 9092
  auto_create_topics_enabled: true
  data_directory: /var/lib/redpanda/data
  developer_mode: true
  kafka_api:
  - address: 0.0.0.0
    port: 9092
  kafka_api_tls:
  - cert_file: /opt/workspace/certs/client-cert.pem
    enabled: true
    key_file: /opt/workspace/certs/client-privkey.pem
    require_client_auth: true
    truststore_file: /opt/workspace/certs/ca-cert.pem
  node_id: 0
  rpc_server:
    address: 0.0.0.0
    port: 33145
  rpc_server_tls:
    cert_file: /opt/workspace/certs/client-cert.pem
    enabled: true
    key_file: /opt/workspace/certs/client-privkey.pem
    require_client_auth: true
    truststore_file: /opt/workspace/certs/ca-cert.pem
  seed_servers: []
rpk:
  coredump_dir: /var/lib/redpanda/coredump
  enable_memory_locking: false
  enable_usage_stats: true
  kafka_api:
    brokers:
    - localhost:9092
    tls:
      cert_file: /opt/workspace/certs/client-cert.pem
      key_file: /opt/workspace/certs/client-privkey.pem
      truststore_file: /opt/workspace/certs/ca-cert.pem
  overprovisioned: true
  tls:
    cert_file: /opt/workspace/certs/client-cert.pem
    key_file: /opt/workspace/certs/client-privkey.pem
    truststore_file: /opt/workspace/certs/ca-cert.pem
  tune_aio_events: false
  tune_ballast_file: false
  tune_clocksource: false
  tune_coredump: false
  tune_cpu: false
  tune_disk_irq: false
  tune_disk_nomerges: false
  tune_disk_scheduler: false
  tune_disk_write_cache: false
  tune_fstrim: false
  tune_network: false
  tune_swappiness: false
  tune_transparent_hugepages: false
schema_registry: {}
